#[derive(Clone, Debug)]
struct Thermal2BridgeProbeCase {
    map: String,
    area_mask: Option<String>,
    sediment_removal_map: Option<String>,
    terrain_width: String,
    terrain_height: String,
    duration: String,
    strength: String,
    anisotropy: String,
    angle: String,
    feature_scale: String,
    sediment_removal: String,
    use_area_mask: bool,
    use_sediment_removal_mask: bool,
}

fn thermal2_bridge_probe_case(name: &str) -> Result<Thermal2BridgeProbeCase, String> {
    let case = match name.to_ascii_lowercase().as_str() {
        "baseline" => Thermal2BridgeProbeCase {
            map: "map:sine:32:5:0.35:0.5".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "flat_identity" => Thermal2BridgeProbeCase {
            map: "map:flat:32:0.5".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "flat_identity_masks" => Thermal2BridgeProbeCase {
            map: "map:flat:32:0.5".to_string(),
            area_mask: Some("map:rampx:32:0:1".to_string()),
            sediment_removal_map: Some("map:radial:32:1:0:0.5:0.5:0.45".to_string()),
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0.35".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "cone_masks" => Thermal2BridgeProbeCase {
            map: "map:cone:32:1:0.5:0.5:0.45".to_string(),
            area_mask: Some("map:rampx:32:0:1".to_string()),
            sediment_removal_map: Some("map:radial:32:1:0:0.5:0.5:0.45".to_string()),
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "duration_zero" => Thermal2BridgeProbeCase {
            map: "map:sine:32:5:0.35:0.5".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "strength_zero" => Thermal2BridgeProbeCase {
            map: "map:sine:32:5:0.35:0.5".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "area_zero_mask" => Thermal2BridgeProbeCase {
            map: "map:sine:32:5:0.35:0.5".to_string(),
            area_mask: Some("map:flat:32:0".to_string()),
            sediment_removal_map: Some("map:radial:32:1:0:0.5:0.5:0.45".to_string()),
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "scalar_sediment" => Thermal2BridgeProbeCase {
            map: "map:rampy:32:0.15:0.95".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.08".to_string(),
            strength: "0.4".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "28".to_string(),
            feature_scale: "40".to_string(),
            sediment_removal: "0.35".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: false,
        },
        "anisotropy_zero" => Thermal2BridgeProbeCase {
            map: "map:checker:32:0.2:0.85:4".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0".to_string(),
            angle: "32".to_string(),
            feature_scale: "25".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "talus_single_level_angle_dead" => Thermal2BridgeProbeCase {
            map: "map:sine:32:5:0.35:0.5".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "75".to_string(),
            feature_scale: "60".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "talus_multilevel_angle_active" => Thermal2BridgeProbeCase {
            map: "map:sine:32:5:0.35:0.5".to_string(),
            area_mask: None,
            sediment_removal_map: None,
            terrain_width: "1000".to_string(),
            terrain_height: "1000".to_string(),
            duration: "0.04".to_string(),
            strength: "0.25".to_string(),
            anisotropy: "0.25".to_string(),
            angle: "75".to_string(),
            feature_scale: "64".to_string(),
            sediment_removal: "0".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: true,
        },
        "world_scale64" => Thermal2BridgeProbeCase {
            map: "map:radial:64:0.92:0.1:0.46:0.53:0.42".to_string(),
            area_mask: Some("map:rampy:64:0.15:1".to_string()),
            sediment_removal_map: None,
            terrain_width: "2048".to_string(),
            terrain_height: "512".to_string(),
            duration: "0.06".to_string(),
            strength: "0.33".to_string(),
            anisotropy: "0.65".to_string(),
            angle: "36".to_string(),
            feature_scale: "75".to_string(),
            sediment_removal: "0.1".to_string(),
            use_area_mask: true,
            use_sediment_removal_mask: false,
        },
        other => return Err(format!("Unknown Thermal2 bridge probe case '{other}'.")),
    };
    Ok(case)
}
