fn transform_compare_cases(cli: &Cli) -> Result<Vec<TransformCompareCase>, String> {
    let matrix = cli.flag("matrix").unwrap_or("focused");
    if matrix.eq_ignore_ascii_case("focused") {
        return Ok(transform_focused_cases());
    }
    Err(format!(
        "Unknown Transform matrix '{matrix}'. Supported matrix: focused."
    ))
}

fn transform_focused_cases() -> Vec<TransformCompareCase> {
    vec![
        transform_case(
            "default_blend_medium_64",
            64,
            1000.0,
            500.0,
            0.5,
            1.25,
            "Eroded",
            "Medium",
            0,
            0.2,
            -0.15,
            1.0,
            true,
            0.85,
            1.0,
            1.0,
            17.0,
            "Blend",
            "None",
            "Medium",
            None,
        ),
        transform_case(
            "identity_none_draft_32",
            32,
            1000.0,
            500.0,
            0.42,
            0.8,
            "Basic",
            "Low",
            11,
            0.0,
            0.0,
            1.0,
            true,
            1.0,
            1.0,
            1.0,
            0.0,
            "None",
            "None",
            "Draft",
            None,
        ),
        transform_case(
            "nonuniform_add_base_64",
            64,
            1600.0,
            700.0,
            0.36,
            1.1,
            "Old",
            "Medium",
            29,
            -0.35,
            0.28,
            0.74,
            false,
            0.92,
            1.35,
            0.72,
            42.0,
            "Add",
            "None",
            "Medium",
            Some("rampx:0.05:0.65"),
        ),
        transform_case(
            "subtract_checker_base_64",
            64,
            1000.0,
            1000.0,
            0.61,
            0.9,
            "Alpine",
            "High",
            77,
            0.18,
            0.22,
            1.18,
            true,
            0.68,
            1.0,
            1.0,
            123.0,
            "Subtract",
            "None",
            "Medium",
            Some("checker:0.2:0.8:7"),
        ),
        transform_case(
            "multiply_rampy_base_96",
            96,
            2400.0,
            900.0,
            0.48,
            1.35,
            "Strata",
            "Medium",
            113,
            -0.12,
            -0.33,
            0.83,
            false,
            1.08,
            0.8,
            1.22,
            273.0,
            "Multiply",
            "None",
            "Medium",
            Some("rampy:0.15:0.95"),
        ),
        transform_case(
            "screen_flat_base_128",
            128,
            1000.0,
            500.0,
            0.31,
            1.6,
            "Eroded",
            "Low",
            211,
            0.42,
            -0.41,
            0.62,
            true,
            1.18,
            1.0,
            1.0,
            318.0,
            "Screen",
            "None",
            "Medium",
            Some("flat:0.24"),
        ),
        transform_case(
            "thin_edge_blend_64",
            64,
            1000.0,
            500.0,
            0.55,
            1.0,
            "Basic",
            "Medium",
            313,
            -0.22,
            0.11,
            1.0,
            true,
            0.77,
            1.0,
            1.0,
            61.0,
            "Blend",
            "Thin",
            "Medium",
            None,
        ),
        transform_case(
            "max_base_high_quality_128",
            128,
            1200.0,
            1200.0,
            0.45,
            1.2,
            "Eroded",
            "High",
            509,
            0.06,
            0.36,
            1.42,
            false,
            0.81,
            1.16,
            0.94,
            207.0,
            "Max",
            "None",
            "High",
            Some("rampx:0.35:0.55"),
        ),
    ]
}

#[allow(clippy::too_many_arguments)]
fn transform_case(
    name: &str,
    resolution: u32,
    terrain_width: f32,
    terrain_height: f32,
    mountain_scale: f32,
    mountain_height: f32,
    mountain_style: &str,
    mountain_bulk: &str,
    seed: i32,
    offset_x: f32,
    offset_y: f32,
    offset_z: f32,
    uniform: bool,
    scale: f32,
    scale_x: f32,
    scale_y: f32,
    rotate: f32,
    blend_mode: &str,
    edges: &str,
    quality: &str,
    base_map: Option<&str>,
) -> TransformCompareCase {
    TransformCompareCase {
        name: name.to_string(),
        resolution: resolution.max(2),
        terrain_width,
        terrain_height,
        mountain_scale,
        mountain_height,
        mountain_style: mountain_style.to_string(),
        mountain_bulk: mountain_bulk.to_string(),
        seed,
        offset_x,
        offset_y,
        offset_z,
        uniform,
        scale,
        scale_x,
        scale_y,
        rotate,
        blend_mode: blend_mode.to_string(),
        edges: edges.to_string(),
        quality: quality.to_string(),
        base_map: base_map.map(str::to_string),
    }
}
