mod agent_picker;
mod chrome;
mod context_menu;
mod effects;
mod launch;
mod layout;
mod list_params;
mod overlay_layout;
mod overlay_targets;
mod row_presentation;
mod session_picker;
mod session_picker_loader;
mod state;
pub(crate) mod theme;
mod thread_row;
mod transcript;
mod work_panel;

pub(crate) use agent_picker::AgentPickerRow;
pub(crate) use chrome::WORKSPACE_CHROME_HEIGHT;
pub(crate) use chrome::WorkspaceChromeAction;
pub(crate) use chrome::WorkspaceChromeBarAreas;
pub(crate) use chrome::WorkspaceChromeMenu;
pub(crate) use chrome::action_at as workspace_chrome_action_at;
pub(crate) use chrome::action_label as workspace_chrome_action_label;
pub(crate) use chrome::action_shortcut as workspace_chrome_action_shortcut;
pub(crate) use chrome::menu_actions as workspace_chrome_menu_actions;
pub(crate) use chrome::menu_at as workspace_chrome_menu_at;
pub(crate) use chrome::menu_bar_areas as workspace_chrome_menu_bar_areas;
pub(crate) use chrome::menu_popup_area as workspace_chrome_menu_popup_area;
pub(crate) use chrome::menu_title as workspace_chrome_menu_title;
pub(crate) use context_menu::workspace_menu_action_at;
pub(crate) use context_menu::workspace_menu_action_disabled;
pub(crate) use context_menu::workspace_menu_action_label;
pub(crate) use context_menu::workspace_menu_actions;
pub(crate) use effects::WorkspaceGatewayEffect;
pub(crate) use effects::WorkspaceMainPaneEffect;
pub(crate) use launch::LaunchStripDropdown;
pub(crate) use launch::LaunchStripDropdownItem;
pub(crate) use launch::LaunchStripDropdownMouseTarget;
pub(crate) use launch::LaunchStripMouseAction;
pub(crate) use launch::LaunchStripState;
pub(crate) use layout::WorkspacePaneSplit;
pub(crate) use layout::workspace_pane_split;
pub(crate) use layout::workspace_toolbar_areas;
pub(crate) use layout::workspace_window_inner_area;
pub(crate) use list_params::workspace_thread_list_params;
pub(crate) use list_params::workspace_token_usage_thread_list_params;
pub(crate) use overlay_layout::workspace_dialog_area;
pub(crate) use overlay_layout::workspace_popup_area;
pub(crate) use overlay_targets::WorkspaceOverlayButtonTarget;
pub(crate) use overlay_targets::workspace_archive_target_at;
pub(crate) use overlay_targets::workspace_delete_target_at;
pub(crate) use overlay_targets::workspace_open_folder_target_at;
pub(crate) use overlay_targets::workspace_rename_target_at;
pub(crate) use row_presentation::WORKSPACE_SUBAGENT_INDENT_STEP;
pub(crate) use row_presentation::workspace_closed_subagents_detail;
pub(crate) use row_presentation::workspace_closed_subagents_label;
pub(crate) use row_presentation::workspace_context_subagent_lines;
pub(crate) use row_presentation::workspace_control_detail;
pub(crate) use row_presentation::workspace_row_control_marker;
pub(crate) use row_presentation::workspace_row_status_label;
pub(crate) use row_presentation::workspace_row_subagent_marker;
pub(crate) use row_presentation::workspace_row_tree_indent;
pub(crate) use row_presentation::workspace_row_tree_prefix;
pub(crate) use session_picker::SessionPickerOpenRequest;
pub(crate) use session_picker::SessionPickerPageRequest;
pub(crate) use state::WorkspaceArchiveConfirmState;
pub(crate) use state::WorkspaceChromeMenuState;
pub(crate) use state::WorkspaceContextMenuState;
pub(crate) use state::WorkspaceDeleteConfirmState;
pub(crate) use state::WorkspaceMenuAction;
pub(crate) use state::WorkspaceOpenFolderState;
pub(crate) use state::WorkspaceOverlay;
pub(crate) use state::WorkspaceRenameState;
pub(crate) use state::WorkspaceState;
pub(crate) use state::WorkspaceVisibleItem;
pub(crate) use theme::WorkspaceTheme;
pub(crate) use theme::WorkspaceThemeKind;
pub(crate) use thread_row::ThreadListRow;
pub(crate) use thread_row::parse_workspace_thread_id;
pub(crate) use thread_row::refresh_workspace_subagent_summaries;
pub(crate) use thread_row::sort_workspace_thread_rows;
pub(crate) use thread_row::workspace_row_is_controlled;
pub(crate) use thread_row::workspace_row_should_auto_observe;
pub(crate) use thread_row::workspace_single_line;
pub(crate) use thread_row::workspace_status_without_control;
pub(crate) use thread_row::workspace_thread_display_name;
pub(crate) use transcript::WorkspaceTranscriptCache;
pub(crate) use transcript::WorkspaceTranscriptRequest;
pub(crate) use transcript::WorkspaceTranscriptTail;
pub(crate) use transcript::WorkspaceTranscriptViewport;
pub(crate) use transcript::lane_width as workspace_transcript_lane_width;
pub(crate) use transcript::render_viewport as render_workspace_transcript_viewport;
pub(crate) use transcript::wrap_lines as wrap_workspace_transcript_lines;
pub(crate) use work_panel::WorkPanelContextState;
pub(crate) use work_panel::WorkPanelControlState;
pub(crate) use work_panel::WorkPanelGoalState;
pub(crate) use work_panel::WorkPanelGoalStatus;
pub(crate) use work_panel::WorkPanelQueueState;
pub(crate) use work_panel::WorkPanelState;
