use chrono::Utc;
use praxis_protocol::ThreadId;
use serde_json::json;
use std::collections::HashSet;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::Ordering;
use tokio::io::AsyncReadExt;
use tokio::io::AsyncWriteExt;
use uuid::Uuid;

use crate::error::PraxisErr;
use crate::error::Result as PraxisResult;
use crate::exec::ExecOutputSpool;
use crate::path_scope::normalize_path_for_scope;

mod artifacts;
mod capability;
mod classification;
mod control_plane;
mod instance;
mod intent;
mod leases;
mod lifecycle;
mod mailbox;
mod managed_commands;
mod paths;
mod persistence;
mod policy;
mod process;
mod rank;
mod records;
mod read_projection;
mod registry;
mod state;
mod tasks;
#[cfg(test)]
mod tests;
mod tickets;

pub(crate) use classification::coordination_scope_for_session_source;
pub(crate) use classification::profile_for_rank;
pub(crate) use classification::rank_for_session_source;
pub(crate) use managed_commands::AgentOsExecutionOpenRequest;
pub(crate) use control_plane::AgentTaskDispatchRequest;
pub(crate) use instance::AgentOs;
pub(crate) use managed_commands::ManagedCommandSpan;
pub(crate) use records::ResourceRequirement;
pub(crate) use records::RuntimeCommandRecord;
pub(crate) use records::RuntimeCommandStatus;
pub(crate) use records::ThreadRegistration;
pub(crate) use records::WorkerRequestCreateRequest;
pub(crate) use records::WorkerRequestRecord;
pub(crate) use records::WorkerRequestStatus;
pub(crate) use process::AgentOsProcessCleaner;
pub(crate) use process::process_runtime_kind;
pub(crate) use process::process_runtime_owner;
pub(crate) use read_projection::AgentOsEventBatch;
pub(crate) use read_projection::AgentOsEventQuery;
pub(crate) use read_projection::AgentOsSnapshot;
pub(crate) use read_projection::AgentOsSnapshotOptions;

use artifacts::append_spool_stream;
use artifacts::metadata_with_blob;
use artifacts::sanitize_artifact_extension;
use classification::artifact_type_for_intent;
use classification::capacity_for_requirement;
use classification::classify_command;
use classification::classify_mutating_tool;
use classification::requires_dirty_audit;
use classification::runtime_kind_for_intent;
use classification::summarize_output;
use classification::validate_task_action_contract;
use managed_commands::audit_git_dirty_files;
use managed_commands::dirty_file_allowed_by_task;
use managed_commands::dirty_file_delta;
use managed_commands::dirty_file_fingerprints;
use managed_commands::format_dirty_file_report;
use managed_commands::push_unique_dirty_files;
use managed_commands::DirtyAuditOutcome;
use managed_commands::ManagedCommandOutputSource;
use records::ActionIntent;
use records::ActionIntentKind;
use records::ArtifactBlobRead;
use records::ArtifactRecord;
use records::ArtifactType;
use records::CapabilityProfile;
use records::CommandIntentPlan;
use records::CommandIntentPlanStatus;
use records::CommandRecord;
use records::EventLedgerEntry;
use records::ExecutionTicket;
use records::LeaseMode;
use records::ManagedProcessRecord;
use records::ManagedProcessStatus;
use records::ResourceLease;
use records::RuntimeCommandType;
use records::ScopedIntents;
use records::ScopedPaths;
use records::TaskRecord;
use records::TaskStatus;
use records::ThreadRegistryEntry;
use records::ThreadRuntimeState;
use paths::action_fingerprint;
use policy::AgentOsPolicy;
use policy::COORDINATOR_RANK;
use policy::HARD_ARTIFACT_READ_MAX_BYTES;
use policy::LEASE_JANITOR_INTERVAL_SECONDS;
use process::cleaner_registry_key;
use process::process_registry_key;
use managed_commands::RuntimeCommandActivity;
use state::AgentOsState;
