use chrono::Utc;
use praxis_protocol::ThreadId;
use serde_json::json;
use std::collections::HashSet;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::Ordering;
use tokio::io::AsyncReadExt;
use tokio::io::AsyncWriteExt;
use uuid::Uuid;

use crate::error::PraxisErr;
use crate::error::Result as PraxisResult;
use crate::exec::ExecOutputSpool;
use crate::path_scope::normalize_path_for_scope;

mod artifact_blobs;
mod artifacts;
mod capability;
mod classification;
mod commands;
mod commands_checkpoint;
mod commands_dirty;
mod commands_finish;
mod control_plane;
mod coordination;
mod dirty;
mod instance;
mod intent;
mod intent_state;
mod leases;
mod lifecycle;
mod managed_commands;
mod model;
mod paths;
mod persistence;
mod policy;
mod process;
mod process_tracking;
mod read_model;
mod read_projection;
mod runtime_command_activity;
mod runtime_command_claims;
mod runtime_command_cleanup;
mod runtime_command_state;
mod runtime_commands;
mod state;
mod tasks;
#[cfg(test)]
mod tests;
mod thread_state;
mod ticket_state;
mod tickets;
mod worker_requests;

pub(crate) use classification::coordination_scope_for_session_source;
pub(crate) use classification::profile_for_rank;
pub(crate) use classification::rank_for_session_source;
pub(crate) use commands::AgentOsExecutionOpenRequest;
pub(crate) use control_plane::AgentTaskDispatchRequest;
pub(crate) use instance::AgentOs;
pub(crate) use managed_commands::ManagedCommandSpan;
pub(crate) use model::ResourceRequirement;
pub(crate) use model::RuntimeCommandRecord;
pub(crate) use model::RuntimeCommandStatus;
pub(crate) use model::ThreadRegistration;
pub(crate) use model::WorkerRequestCreateRequest;
pub(crate) use model::WorkerRequestRecord;
pub(crate) use model::WorkerRequestStatus;
pub(crate) use process::AgentOsProcessCleaner;
pub(crate) use process::process_runtime_kind;
pub(crate) use process::process_runtime_owner;
pub(crate) use read_projection::AgentOsEventBatch;
pub(crate) use read_projection::AgentOsEventQuery;
pub(crate) use read_projection::AgentOsSnapshot;
pub(crate) use read_projection::AgentOsSnapshotOptions;

use artifacts::append_spool_stream;
use artifacts::metadata_with_blob;
use artifacts::sanitize_artifact_extension;
use classification::artifact_type_for_intent;
use classification::capacity_for_requirement;
use classification::classify_command;
use classification::classify_mutating_tool;
use classification::requires_dirty_audit;
use classification::runtime_kind_for_intent;
use classification::summarize_output;
use classification::validate_task_action_contract;
use dirty::audit_git_dirty_files;
use dirty::dirty_file_allowed_by_task;
use dirty::dirty_file_delta;
use dirty::dirty_file_fingerprints;
use dirty::format_dirty_file_report;
use dirty::push_unique_dirty_files;
use managed_commands::DirtyAuditOutcome;
use managed_commands::ManagedCommandOutputSource;
use model::ActionIntent;
use model::ActionIntentKind;
use model::ArtifactBlobRead;
use model::ArtifactRecord;
use model::ArtifactType;
use model::CapabilityProfile;
use model::CommandIntentPlan;
use model::CommandIntentPlanStatus;
use model::CommandRecord;
use model::EventLedgerEntry;
use model::ExecutionTicket;
use model::LeaseMode;
use model::ManagedProcessRecord;
use model::ManagedProcessStatus;
use model::ResourceLease;
use model::RuntimeCommandType;
use model::ScopedIntents;
use model::ScopedPaths;
use model::TaskRecord;
use model::TaskStatus;
use model::ThreadRegistryEntry;
use model::ThreadRuntimeState;
use paths::action_fingerprint;
use policy::AgentOsPolicy;
use policy::COORDINATOR_RANK;
use policy::HARD_ARTIFACT_READ_MAX_BYTES;
use policy::LEASE_JANITOR_INTERVAL_SECONDS;
use process::cleaner_registry_key;
use process::process_registry_key;
use runtime_command_state::RuntimeCommandActivity;
use state::AgentOsState;
