//! Root of the `praxis-core` library.

// Session startup composes deep async service graphs across exec, MCP, and network proxy code.
#![recursion_limit = "256"]
// Prevent accidental direct writes to stdout/stderr in library code. All
// user-visible output must go through the appropriate abstraction (e.g.,
// the TUI or the tracing stack).
#![deny(clippy::print_stdout, clippy::print_stderr)]

pub mod api_bridge;
mod apply_patch;
mod apps;
mod arc_monitor;
mod auth_env_telemetry;
mod auto_summary;
mod auto_title;
mod auto_title_profile;
pub mod capabilities;
mod client;
mod client_common;
mod llm;
mod path_scope;
pub mod praxis;
mod prompt_profiles;
mod provider_failure;
mod realtime_context;
mod realtime_conversation;
pub use praxis::SteerInputError;
mod compact_remote;
mod praxis_thread;
pub use praxis_thread::PraxisThread;
pub use praxis_thread::ThreadConfigSnapshot;
mod agent;
pub(crate) mod agent_os;
mod command_canonicalization;
mod commit_attribution;
pub mod config;
pub mod config_loader;
pub mod connectors;
mod context_manager;
mod contextual_user_message;
mod environment_context;
pub mod error;
pub mod exec;
pub mod exec_env;
mod exec_policy;
pub mod external_agent_migration;
pub mod file_watcher;
mod flags;
#[cfg(test)]
mod git_info_tests;
mod goals;
mod guardian;
mod heartbeats;
mod history_preview;
mod hook_runtime;
pub mod instructions;
pub mod landlock;
pub mod mcp;
mod mcp_skill_dependencies;
mod mcp_tool_approval_templates;
pub mod models_manager;
mod network_policy_decision;
pub mod network_proxy_loader;
mod original_image_detail;
mod praxis_delegate;
pub use text_encoding::bytes_to_string_smart;
mod mcp_tool_call;
mod memories;
pub mod mention_syntax;
pub mod message_history;
pub mod thread_cost;
pub mod token_saver_report;
pub mod utils;
pub use utils::path_utils;
pub mod personality_migration;
pub mod plugins;
mod provider_auth;
pub(crate) mod mentions {
    pub(crate) use crate::plugins::build_connector_slug_counts;
    pub(crate) use crate::plugins::build_skill_name_counts;
    pub(crate) use crate::plugins::collect_explicit_app_ids;
    pub(crate) use crate::plugins::collect_explicit_plugin_mentions;
    pub(crate) use crate::plugins::collect_tool_mentions_from_messages;
}
mod sandbox_tags;
pub mod sandboxing;
mod session_prefix;
mod session_startup_prewarm;
pub mod skills;
pub(crate) use skills::SkillError;
pub(crate) use skills::SkillInjections;
pub(crate) use skills::SkillLoadOutcome;
pub(crate) use skills::SkillMetadata;
pub(crate) use skills::SkillsLoadInput;
pub(crate) use skills::SkillsManager;
pub(crate) use skills::build_skill_injections;
pub(crate) use skills::build_skill_name_counts;
pub(crate) use skills::collect_env_var_dependencies;
pub(crate) use skills::collect_explicit_skill_mentions;
pub(crate) use skills::config_rules;
pub(crate) use skills::injection;
pub(crate) use skills::loader;
pub(crate) use skills::manager;
pub(crate) use skills::maybe_emit_implicit_skill_invocation;
pub(crate) use skills::render_skills_section;
pub(crate) use skills::resolve_skill_dependencies_for_turn;
pub(crate) use skills::skills_load_input_from_config;
mod skills_watcher;
pub mod test_support;
mod text_encoding;
pub mod transcription;
mod turn_assistant_text;
#[cfg(test)]
mod turn_completed_output;
mod turn_final_answer;
mod turn_image_output;
mod turn_output_items;
mod unified_exec;
pub mod windows_sandbox;
pub use client::X_RESPONSESAPI_INCLUDE_TIMING_METRICS_HEADER;
pub use llm::provider::ANTHROPIC_API_BASE_URL;
pub use llm::provider::ANTHROPIC_API_KEY_ENV_VAR;
pub use llm::provider::ANTHROPIC_API_VERSION;
pub use llm::provider::ANTHROPIC_PROVIDER_ID;
pub use llm::provider::DEEPSEEK_PROVIDER_ID;
pub use llm::provider::DEFAULT_LMSTUDIO_PORT;
pub use llm::provider::DEFAULT_OLLAMA_PORT;
pub use llm::provider::FirstPartyModelOwner;
pub use llm::provider::KIMI_API_BASE_URL;
pub use llm::provider::KIMI_API_KEY_ENV_VAR;
pub use llm::provider::KIMI_PROVIDER_ID;
pub use llm::provider::LMSTUDIO_OSS_PROVIDER_ID;
pub use llm::provider::ModelProviderInfo;
pub use llm::provider::NATIVE_LOCAL_PROVIDER_ID;
pub use llm::provider::OLLAMA_OSS_PROVIDER_ID;
pub use llm::provider::OPENAI_PROVIDER_ID;
pub use llm::provider::built_in_model_providers;
pub use llm::provider::create_oss_provider_with_base_url;
pub use llm::provider::first_party_model_owner;
pub use llm::provider::provider_accepts_known_first_party_model;
pub use llm::provider::provider_accepts_registered_model_catalog;
pub use llm::wire::ModelProviderCompatInfo;
pub use llm::wire::ModelProviderMaxTokensField;
pub use llm::wire::ModelProviderReasoningEffortMap;
pub use llm::wire::ModelProviderThinkingFormat;
pub use llm::wire::WireApi;
mod event_mapping;
mod response_debug_context;
pub mod review_format;
pub mod review_prompts;
mod thread_manager;
pub mod web_search;
pub mod windows_sandbox_read_grants;
pub use thread_manager::ThreadForkSnapshot;
pub use thread_manager::ThreadManager;
pub use thread_manager::ThreadShutdownReport;
pub use thread_manager::ThreadSpawnResult;
pub mod project_doc;
mod rollout;
pub(crate) mod safety;
pub mod seatbelt;
mod session_rollout_init_error;
pub mod shell;
pub mod shell_snapshot;
pub mod spawn;
pub mod state_db_bridge;
mod thread_rollout_truncation;
mod tools;
pub mod turn_diff_tracker;
mod turn_metadata;
mod turn_timing;
pub use rollout::ARCHIVED_SESSIONS_SUBDIR;
pub use rollout::INTERACTIVE_SESSION_SOURCES;
pub use rollout::ListThreadsQuery;
pub use rollout::RolloutRecorder;
pub use rollout::RolloutRecorderParams;
pub use rollout::SESSIONS_SUBDIR;
pub use rollout::SessionMeta;
pub use rollout::ThreadNameResolver;
pub use rollout::ThreadNameWriter;
pub use rollout::ThreadStore;
pub use rollout::ThreadSummary;
pub use rollout::ThreadSummaryPage;
pub use rollout::list::Cursor;
pub use rollout::list::ThreadItem;
pub use rollout::list::ThreadSortKey;
pub use rollout::list::ThreadsPage;
pub use rollout::list::parse_cursor;
pub use rollout::list::read_head_for_summary;
pub use rollout::list::read_session_meta_line;
pub use rollout::list_threads;
pub use rollout::policy::EventPersistenceMode;
pub use rollout::rollout_date_parts;
mod function_tool;
mod state;
mod tasks;
mod user_shell_command;
pub mod util;

pub use client::ModelClient;
pub use client::ModelClientSession;
pub use client::X_PRAXIS_TURN_METADATA_HEADER;
pub use client_common::Prompt;
pub use client_common::REVIEW_PROMPT;
pub use client_common::ResponseEvent;
pub use client_common::ResponseStream;
pub use compact::content_items_to_text;
pub use event_mapping::parse_turn_item;
pub use exec_policy::ExecPolicyError;
pub use exec_policy::check_execpolicy_for_warnings;
pub use exec_policy::format_exec_policy_error_with_source;
pub use exec_policy::load_exec_policy;
pub use file_watcher::FileWatcherEvent;
pub use turn_metadata::build_turn_metadata_header;
pub mod compact;
pub mod memory_trace;
pub mod otel_init;
