use std::path::PathBuf;

use praxis_app_gateway_protocol::CollabAgentState as ApiCollabAgentState;
use praxis_app_gateway_protocol::CollabAgentStatus as ApiCollabAgentStatus;
use praxis_app_gateway_protocol::CollabAgentTool;
use praxis_app_gateway_protocol::CollabAgentToolCallStatus as ApiCollabAgentToolCallStatus;
use praxis_app_gateway_protocol::CommandAction;
use praxis_app_gateway_protocol::CommandExecutionSource;
use praxis_app_gateway_protocol::CommandExecutionStatus as ApiCommandExecutionStatus;
use praxis_app_gateway_protocol::ErrorNotification;
use praxis_app_gateway_protocol::FileUpdateChange as ApiFileUpdateChange;
use praxis_app_gateway_protocol::ItemCompletedNotification;
use praxis_app_gateway_protocol::ItemStartedNotification;
use praxis_app_gateway_protocol::McpToolCallError;
use praxis_app_gateway_protocol::McpToolCallResult;
use praxis_app_gateway_protocol::McpToolCallStatus as ApiMcpToolCallStatus;
use praxis_app_gateway_protocol::PatchApplyStatus as ApiPatchApplyStatus;
use praxis_app_gateway_protocol::PatchChangeKind as ApiPatchChangeKind;
use praxis_app_gateway_protocol::ServerNotification;
use praxis_app_gateway_protocol::ThreadItem;
use praxis_app_gateway_protocol::ThreadTokenUsage;
use praxis_app_gateway_protocol::TokenUsageBreakdown;
use praxis_app_gateway_protocol::Turn;
use praxis_app_gateway_protocol::TurnCompletedNotification;
use praxis_app_gateway_protocol::TurnError;
use praxis_app_gateway_protocol::TurnPlanStep;
use praxis_app_gateway_protocol::TurnPlanStepStatus;
use praxis_app_gateway_protocol::TurnPlanUpdatedNotification;
use praxis_app_gateway_protocol::TurnStartedNotification;
use praxis_app_gateway_protocol::TurnStatus;
use praxis_app_gateway_protocol::WebSearchAction as ApiWebSearchAction;
use praxis_protocol::ThreadId;
use praxis_protocol::models::WebSearchAction;
use praxis_protocol::protocol::AskForApproval;
use praxis_protocol::protocol::SandboxPolicy;
use praxis_protocol::protocol::SessionConfiguredEvent;
use pretty_assertions::assert_eq;
use serde_json::json;

use praxis_exec::event_processor_with_jsonl_output::CollectedThreadEvents;
use praxis_exec::event_processor_with_jsonl_output::EventProcessorWithJsonOutput;
use praxis_exec::event_processor_with_jsonl_output::PraxisStatus;
use praxis_exec::exec_events::AgentMessageItem;
use praxis_exec::exec_events::CollabAgentState;
use praxis_exec::exec_events::CollabAgentStatus;
use praxis_exec::exec_events::CollabTool;
use praxis_exec::exec_events::CollabToolCallItem;
use praxis_exec::exec_events::CollabToolCallStatus;
use praxis_exec::exec_events::CommandExecutionItem;
use praxis_exec::exec_events::CommandExecutionStatus;
use praxis_exec::exec_events::ErrorItem;
use praxis_exec::exec_events::FileChangeItem;
use praxis_exec::exec_events::FileUpdateChange as ExecFileUpdateChange;
use praxis_exec::exec_events::ItemCompletedEvent;
use praxis_exec::exec_events::ItemStartedEvent;
use praxis_exec::exec_events::ItemUpdatedEvent;
use praxis_exec::exec_events::McpToolCallItem;
use praxis_exec::exec_events::McpToolCallItemError;
use praxis_exec::exec_events::McpToolCallItemResult;
use praxis_exec::exec_events::McpToolCallStatus;
use praxis_exec::exec_events::PatchApplyStatus;
use praxis_exec::exec_events::PatchChangeKind;
use praxis_exec::exec_events::ReasoningItem;
use praxis_exec::exec_events::ThreadErrorEvent;
use praxis_exec::exec_events::ThreadEvent;
use praxis_exec::exec_events::ThreadItem as ExecThreadItem;
use praxis_exec::exec_events::ThreadItemDetails;
use praxis_exec::exec_events::ThreadStartedEvent;
use praxis_exec::exec_events::TodoItem;
use praxis_exec::exec_events::TodoListItem;
use praxis_exec::exec_events::TurnCompletedEvent;
use praxis_exec::exec_events::TurnFailedEvent;
use praxis_exec::exec_events::TurnStartedEvent;
use praxis_exec::exec_events::Usage;
use praxis_exec::exec_events::WebSearchItem;

mod collab_files_messages;
mod lifecycle;
mod plan_and_usage;
mod reasoning_search_mcp;
mod turn_completion;
